In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("HR_Data.csv")

In [3]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [4]:
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [5]:
df["YearsWithCurrManager"] = df["YearsWithCurrManager"].fillna(
    df["YearsWithCurrManager"].median()
)

In [6]:
df.duplicated().sum()

7

In [7]:
df = df.drop_duplicates()

In [8]:
df.drop(
    columns=[
        "EmployeeCount",
        "Over18",
        "StandardHours"
    ],
    inplace=True
)

In [9]:
df.dtypes

EmpID                        object
Age                           int64
AgeGroup                     object
Attrition                    object
BusinessTravel               object
DailyRate                     int64
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
EmployeeNumber                int64
EnvironmentSatisfaction       int64
Gender                       object
HourlyRate                    int64
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                 int64
SalarySlab                   object
MonthlyRate                   int64
NumCompaniesWorked            int64
OverTime                     object
PercentSalaryHike             int64
PerformanceRating             int64
RelationshipSatisfaction      int64
StockOptionLevel              int64
TotalWorkingYears             int64
TrainingTimesLastYear         int64
WorkLifeBalance               int64
YearsAtCompany                int64
YearsInCurrentRole            int64
YearsSinceLastPromotion       int64
YearsWithCurrManager        float64
dtype: object

In [10]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print("-"*50)

EmpID
['RM297' 'RM302' 'RM458' ... 'RM537' 'RM880' 'RM1210']
--------------------------------------------------
Age
[18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]
--------------------------------------------------
AgeGroup
['18-25' '26-35' '36-45' '46-55' '55+']
--------------------------------------------------
Attrition
['Yes' 'No']
--------------------------------------------------
BusinessTravel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel' 'TravelRarely']
--------------------------------------------------
DailyRate
[ 230  812 1306  287  247 1124  544 1431  528 1181  602  303  489  419
  645  504  265  871  959 1362  500  129 1097  769  805  654 1141  727
  391  996  756  895  156 1343 1427 1334  984  251  546  337  501 1123
  534  594 1256 1136  253 1368  604 1230  617  217  457 1294  581  541
 1309  885  650  310 1243  373  507  977 1320  427  160  571  638  673
  813 1353 1127 1371 1448  535  691  823 1287  693 1092 1269 1206  477
 1476  381  830  350  567  240  506  897  771 1280  685  675  891  688
  622  810  883  180  141  583  867 1219 1356  599  266  882 1372  949
  383  772  309 1382 1357 1443  841 1355 1479  496 1449  950  933  575
 1349  426  775  471  703  991 1146  887 1283 1066  342  921  192 1330
 1384  683  652  474  786  390  920  572  482 1096  157 1167  591 1240
  994 1450 1157  894  472 1242 1220 1377  210 1130 1469  798 1420 1115
 1410  608  294  975  829  269  443  618 1134 1055 1277  199 1103 1291
  793  205  135 1302  486 1054 1297  728 1131  511 1354 1337  954  155
  103 1434  120  440  529 1158 1117  304 1300  890  760 1169  821  995
 1144 1366  857 1009 1451  773 1485 1179  791  193  640  736  866 1496
  289 1423  467 1083  329  580 1217  280 1172  783 1475 1404  153 1389
 1328  121  992 1413  896  665 1247 1210  442  318  738  144  746  986
  408  232 1176  806 1396 1090  657 1252  341 1086  906 1107  490  718
 1401  942 1010 1329  694  332  115 1246  410  224  441  598 1370  469
 1082  428  461  590  574  726  352  459  592  136 1378  468 1358  125
  721  852  288 1312  438  201 1339  111 1005  334 1275  570  641  202
  464  317 1400 1398 1116  413  448  946 1012  231  138  109  853 1465
  879 1138  634  855  990  330  740 1288  241  600  979  305  945  911
  670  655  249  542  140 1327  307 1463  444  218  106 1232  480 1274
  828 1365  525 1222  154 1188  616  335  874 1332 1062  587 1060  667
  182  326 1445  523  561  715 1112  741  163 1003 1079  196 1125  359
  311  976  754 1276  697 1154  325  548 1093  827 1033  689  967 1045
  515 1311  128  588 1018 1474  646  929  430  859  117  300  379  374
 1184  498 1109  862  116 1316 1089  499  601  495  824 1200 1259  585
  964  371  953 1318  414  238 1373  267  234  801 1392  924  750  134
  931  147  465  832  553  508  922 1216 1296 1076  527  213  118  586
 1075 1198 1069  722 1038 1017  970  603  536 1111 1099  516  589  392
  530  211 1303 1313 1346  699 1065 1153  658 1031  629  878  470 1381
  296  988  258  254  204 1397 1442  167  702  216 1333  669  131  648
  943  999  285  404  560  401 1326  790  971 1440  479 1351  653  678
  181 1375 1480  735  937 1239  704  628  809 1229 1142  664  776 1214
  662  556  944 1315  755  619  195  538 1225  384 1258  607  130  672
 1137  802 1204 1182  982  819  636 1361 1212  817  200  660 1029 1402
  104  208  737  763  880  146 1180  185  219  682 1224 1490 1395 1199
 1299 1218 1223 1195  132 1467  635 1403  566 1105  845  164  913  676
 1041  928 1278 1425  188  938  796  917  363  429 1174  172  884  559
  711 1040 1456 1383 1266 1213  557  301 1120  397  807 1189  290  663
  319  228  889 1192 1319 1305 1063  799  142  446  558 1231  625  124
  367 1439 1462  674  671 1470  370  161  573  364 1380 1261 1084  119
  322  849  343 1495  362  243  168  268  395  152 1391 1035 1186  770
  433  888  903 1245  437  148  833 1336  723 1394 1444 1321  345  505
 1132 1162 1122  466  203  439  412  360  524 1498 1387  170  492  792
 1253  766  835 1251  105  613  630  989  905 1151 1416 1171  759  555
  302 1094  804  720 1492 1308  593  902  107  299  458 1202 1342  898
  369  611 1194  692  543 1322 1102 1360 1411  483  143  509  314 1085
  263  840  549  256  918  552  447  642  582  930  926  532  916  932
 1271 1265  462  481  647  179 1147  748 1059 1128  355 1273  394  957
 1344 1034 1001  313 1473  782  422  177  415  531  244 1422 1459 1488
  661 1376  621  935  981 1193 1037  194 1268 1052  252 1385 1249  306
  974  248 1234  788 1050 1457 1015  336 1238  176  705 1211  526  644
  488  406  150  377  563  717  734  261  706 1254  666 1482  983  719
 1454 1379  955  207  626 1236  277 1262  969 1221 1108  365  708  279
 1002 1091 1418  174 1098  271 1064 1023  869 1452  328  854  797 1046
 1207  562  316  881 1126  939  145 1464 1421  333  264  432  632  684
 1150 1178 1323  237  968 1405  956 1325 1053 1030 1282 1436 1070  346
  868  102 1168  376 1441  966  584  431  836  452  725  436  282  478
  189  713  206 1369 1255  405 1145  286  781 1272  848  605 1324 1435
  818 1429 1499  696]
--------------------------------------------------
Department
['Research & Development' 'Sales' 'Human Resources']
--------------------------------------------------
DistanceFromHome
[ 3 10  5  8  1 14 22  2 21  9 25  6  4 11 15 12 18  7 16 19 26 20 24 23
 17 13 29 28 27]
--------------------------------------------------
Education
[3 2 1 4 5]
--------------------------------------------------
EducationField
['Life Sciences' 'Medical' 'Marketing' 'Technical Degree' 'Other'
 'Human Resources']
--------------------------------------------------
EmployeeNumber
[ 405  411  614 ...  732 1233 1697]
--------------------------------------------------
EnvironmentSatisfaction
[3 4 2 1]
--------------------------------------------------
Gender
['Male' 'Female']
--------------------------------------------------
HourlyRate
[ 54  69  73  80  97  70  33  50  79 100  47  52  37  96  57  66  83  32
  49  84  98  87  43  31  99  39  90  65  36  45  58  59  60  34  94  48
  85  75  63  62  93  51  78  61  77  38  89  55  46  41  42  91  64  40
  67  81  68  82  71  88  53  76  95  30  74  56  86  44  92  72  35]
--------------------------------------------------
JobInvolvement
[3 2 1 4]
--------------------------------------------------
JobLevel
[1 2 3 4 5]
--------------------------------------------------
JobRole
['Laboratory Technician' 'Sales Representative' 'Research Scientist'
 'Human Resources' 'Manufacturing Director' 'Sales Executive'
 'Healthcare Representative' 'Research Director' 'Manager']
--------------------------------------------------
JobSatisfaction
[3 2 4 1]
--------------------------------------------------
MaritalStatus
['Single' 'Divorced' 'Married']
--------------------------------------------------
MonthlyIncome
[ 1420  1200  1878 ... 10266  5220 10883]
--------------------------------------------------
SalarySlab
['Upto 5k' '5k-10k' '10k-15k' '15k+']
--------------------------------------------------
MonthlyRate
[25233  9724  8059 ... 11924 10893 20467]
--------------------------------------------------
NumCompaniesWorked
[1 0 5 6 3 2 9 8 7 4]
--------------------------------------------------
OverTime
['No' 'Yes']
--------------------------------------------------
PercentSalaryHike
[13 12 14 15 16 19 21 22 25 18 11 17 24 20 23]
--------------------------------------------------
PerformanceRating
[3 4]
--------------------------------------------------
RelationshipSatisfaction
[3 1 4 2]
--------------------------------------------------
StockOptionLevel
[0 2 1 3]
--------------------------------------------------
TotalWorkingYears
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 28 27 29 31 30 32 33 34 35 36 37 38 40]
--------------------------------------------------
TrainingTimesLastYear
[2 3 0 5 4 6 1]
--------------------------------------------------
WorkLifeBalance
[3 4 1 2]
--------------------------------------------------
YearsAtCompany
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24
 25 23 26 31 27 32 30 29 33 34 36 37 40]
--------------------------------------------------
YearsInCurrentRole
[ 0  1  2  3  4  5  7  8  6  9 10 12 13 14 11 15 16 17 18]
--------------------------------------------------
YearsSinceLastPromotion
[ 0  1  2  3  5  4  7  6  8 10  9 11 12 15 13 14]
--------------------------------------------------
YearsWithCurrManager
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 12. 13. 11. 15. 14. 17. 16.]
--------------------------------------------------

In [11]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[18,25,35,45,55,65],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65"
    ]
)

In [12]:
df["IncomeBand"] = pd.cut(
    df["MonthlyIncome"],
    bins=[0,5000,10000,15000,20000,50000],
    labels=[
        "0-5K",
        "5K-10K",
        "10K-15K",
        "15K-20K",
        "20K+"
    ]
)

In [13]:
df["TenureGroup"] = pd.cut(
    df["YearsAtCompany"],
    bins=[0,2,5,10,20,40],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "11-20 Years",
        "20+ Years"
    ]
)

In [14]:
df.shape

(1473, 37)

In [15]:
df.duplicated().sum()

0

In [31]:
df = pd.read_csv("HR_Data_Cleaned.csv")

In [32]:
df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,405,...,3,3,0,0,2,3,0,0,0,0.0
1,RM302,18,No,Travel_Rarely,812,Sales,10,3,Medical,411,...,3,1,0,0,2,3,0,0,0,0.0
2,RM458,18,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,614,...,3,4,0,0,3,3,0,0,0,0.0
3,RM728,18,No,Non-Travel,287,Research & Development,5,2,Life Sciences,1012,...,3,4,0,0,2,3,0,0,0,0.0
4,RM829,18,Yes,Non-Travel,247,Research & Development,8,1,Medical,1156,...,3,4,0,0,0,3,0,0,0,0.0

In [35]:
df["Education"] = df["Education"].map({
    1: "Below College",
    2: "College",
    3: "Bachelor",
    4: "Master",
    5: "Doctor"
})

In [36]:
df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EducationLevel
0,RM297,18,Yes,Travel_Rarely,230,Research & Development,3,Bachelor,Life Sciences,405,...,3,0,0,2,3,0,0,0,0.0,Bachelor
1,RM302,18,No,Travel_Rarely,812,Sales,10,Bachelor,Medical,411,...,1,0,0,2,3,0,0,0,0.0,Bachelor
2,RM458,18,Yes,Travel_Frequently,1306,Sales,5,Bachelor,Marketing,614,...,4,0,0,3,3,0,0,0,0.0,Bachelor
3,RM728,18,No,Non-Travel,287,Research & Development,5,College,Life Sciences,1012,...,4,0,0,2,3,0,0,0,0.0,College
4,RM829,18,Yes,Non-Travel,247,Research & Development,8,Below College,Medical,1156,...,4,0,0,0,3,0,0,0,0.0,Below College

In [37]:
df["JobInvolvementLevel"] = df["JobInvolvement"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [38]:
df["JobInvolvement"] = df["JobInvolvement"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [40]:
df.head().describe()

,Age,DailyRate,DistanceFromHome,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,5.0,5.000000,5.000000,5.000000,5.00000,5.000000,5.0,5.000000,5.000000,5.000000,...,5.0,5.00000,5.0,5.0,5.000000,5.0,5.0,5.0,5.0,5.0
mean,18.0,576.400000,6.200000,719.600000,2.80000,69.000000,1.0,3.000000,1490.600000,14013.000000,...,3.0,3.20000,0.0,0.0,1.800000,3.0,0.0,0.0,0.0,0.0
std,0.0,474.360939,2.774887,346.879374,0.83666,9.513149,0.0,0.707107,388.477541,6712.177106,...,0.0,1.30384,0.0,0.0,1.095445,0.0,0.0,0.0,0.0,0.0
min,18.0,230.000000,3.000000,405.000000,2.00000,54.000000,1.0,2.000000,1051.000000,8059.000000,...,3.0,1.00000,0.0,0.0,0.000000,3.0,0.0,0.0,0.0,0.0
25%,18.0,247.000000,5.000000,411.000000,2.00000,69.000000,1.0,3.000000,1200.000000,9724.000000,...,3.0,3.00000,0.0,0.0,2.000000,3.0,0.0,0.0,0.0,0.0
50%,18.0,287.000000,5.000000,614.000000,3.00000,69.000000,1.0,3.000000,1420.000000,13493.000000,...,3.0,4.00000,0.0,0.0,2.000000,3.0,0.0,0.0,0.0,0.0
75%,18.0,812.000000,8.000000,1012.000000,3.00000,73.000000,1.0,3.000000,1878.000000,13556.000000,...,3.0,4.00000,0.0,0.0,2.000000,3.0,0.0,0.0,0.0,0.0
max,18.0,1306.000000,10.000000,1156.000000,4.00000,80.000000,1.0,4.000000,1904.000000,25233.000000,...,3.0,4.00000,0.0,0.0,3.000000,3.0,0.0,0.0,0.0,0.0

In [41]:
df["JobLevelName"] = df["JobLevel"].map({
    1: "Entry Level",
    2: "Junior",
    3: "Mid Level",
    4: "Senior",
    5: "Executive"
})

In [42]:
df["JobLevel"] = df["JobLevel"].map({
    1: "Entry Level",
    2: "Junior",
    3: "Mid Level",
    4: "Senior",
    5: "Executive"
})

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1473 entries, 0 to 1472
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1473 non-null   object
 1   Age                       1473 non-null   int64
 2   Attrition                 1473 non-null   object
 3   BusinessTravel            1473 non-null   object
 4   DailyRate                 1473 non-null   int64
 5   Department                1473 non-null   object
 6   DistanceFromHome          1473 non-null   int64
 7   Education                 1473 non-null   object
 8   EducationField            1473 non-null   object
 9   EmployeeNumber            1473 non-null   int64
 10  EnvironmentSatisfaction   1473 non-null   int64
 11  Gender                    1473 non-null   object
 12  HourlyRate                1473 non-null   int64
 13  JobInvolvement            1473 non-null   object
 14  JobLevel                  1473 non-null   object
 15  JobRole                   1473 non-null   object
 16  JobSatisfaction           1473 non-null   int64
 17  MaritalStatus             1473 non-null   object
 18  MonthlyIncome             1473 non-null   int64
 19  SalarySlab                1473 non-null   object
 20  MonthlyRate               1473 non-null   int64
 21  NumCompaniesWorked        1473 non-null   int64
 22  OverTime                  1473 non-null   object
 23  PercentSalaryHike         1473 non-null   int64
 24  PerformanceRating         1473 non-null   int64
 25  RelationshipSatisfaction  1473 non-null   int64
 26  StockOptionLevel          1473 non-null   int64
 27  TotalWorkingYears         1473 non-null   int64
 28  TrainingTimesLastYear     1473 non-null   int64
 29  WorkLifeBalance           1473 non-null   int64
 30  YearsAtCompany            1473 non-null   int64
 31  YearsInCurrentRole        1473 non-null   int64
 32  YearsSinceLastPromotion   1473 non-null   int64
 33  YearsWithCurrManager      1473 non-null   float64
 34  EducationLevel            1473 non-null   object
 35  JobInvolvementLevel       1473 non-null   object
 36  JobLevelName              1473 non-null   object
dtypes: float64(1), int64(20), object(16)
memory usage: 425.9+ KB

In [44]:
df["JobSatisfactionLevel"] = df["JobSatisfaction"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [45]:
df["JobSatisfaction"] = df["JobSatisfaction"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [46]:
df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EducationLevel,JobInvolvementLevel,JobLevelName,JobSatisfactionLevel
0,RM297,18,Yes,Travel_Rarely,230,Research & Development,3,Bachelor,Life Sciences,405,...,2,3,0,0,0,0.0,Bachelor,High,Entry Level,High
1,RM302,18,No,Travel_Rarely,812,Sales,10,Bachelor,Medical,411,...,2,3,0,0,0,0.0,Bachelor,Medium,Entry Level,High
2,RM458,18,Yes,Travel_Frequently,1306,Sales,5,Bachelor,Marketing,614,...,3,3,0,0,0,0.0,Bachelor,High,Entry Level,Medium
3,RM728,18,No,Non-Travel,287,Research & Development,5,College,Life Sciences,1012,...,2,3,0,0,0,0.0,College,High,Entry Level,Very High
4,RM829,18,Yes,Non-Travel,247,Research & Development,8,Below College,Medical,1156,...,0,3,0,0,0,0.0,Below College,High,Entry Level,High

In [47]:
df["PerformanceRating"] = df["PerformanceRating"].map({
    3: "Meets Expectations",
    4: "Outstanding"
})

In [48]:
df["RelationshipSatisfaction"] = df["RelationshipSatisfaction"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [49]:
df["StockOptionLevel"] = df["StockOptionLevel"].map({
    0: "No Stock Option",
    1: "Low",
    2: "Medium",
    3: "High"
})

In [50]:
df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EducationLevel,JobInvolvementLevel,JobLevelName,JobSatisfactionLevel
0,RM297,18,Yes,Travel_Rarely,230,Research & Development,3,Bachelor,Life Sciences,405,...,2,3,0,0,0,0.0,Bachelor,High,Entry Level,High
1,RM302,18,No,Travel_Rarely,812,Sales,10,Bachelor,Medical,411,...,2,3,0,0,0,0.0,Bachelor,Medium,Entry Level,High
2,RM458,18,Yes,Travel_Frequently,1306,Sales,5,Bachelor,Marketing,614,...,3,3,0,0,0,0.0,Bachelor,High,Entry Level,Medium
3,RM728,18,No,Non-Travel,287,Research & Development,5,College,Life Sciences,1012,...,2,3,0,0,0,0.0,College,High,Entry Level,Very High
4,RM829,18,Yes,Non-Travel,247,Research & Development,8,Below College,Medical,1156,...,0,3,0,0,0,0.0,Below College,High,Entry Level,High

In [51]:
df["WorkLifeBalance"] = df["WorkLifeBalance"].map({
    1: "Bad",
    2: "Good",
    3: "Better",
    4: "Best"
})

In [52]:
df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EducationLevel,JobInvolvementLevel,JobLevelName,JobSatisfactionLevel
0,RM297,18,Yes,Travel_Rarely,230,Research & Development,3,Bachelor,Life Sciences,405,...,2,Better,0,0,0,0.0,Bachelor,High,Entry Level,High
1,RM302,18,No,Travel_Rarely,812,Sales,10,Bachelor,Medical,411,...,2,Better,0,0,0,0.0,Bachelor,Medium,Entry Level,High
2,RM458,18,Yes,Travel_Frequently,1306,Sales,5,Bachelor,Marketing,614,...,3,Better,0,0,0,0.0,Bachelor,High,Entry Level,Medium
3,RM728,18,No,Non-Travel,287,Research & Development,5,College,Life Sciences,1012,...,2,Better,0,0,0,0.0,College,High,Entry Level,Very High
4,RM829,18,Yes,Non-Travel,247,Research & Development,8,Below College,Medical,1156,...,0,Better,0,0,0,0.0,Below College,High,Entry Level,High

In [53]:
df.to_csv("HR_Data_Again_Cleaned.csv", index=False)

In [54]:
df["EnvironmentSatisfaction"] = df["EnvironmentSatisfaction"].map({
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
})

In [55]:
df.to_csv("HR_Data_Final.csv", index=False)